version: "3.8"

services:

  db:
    image: mysql:8.0
    container_name: medapp_db
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password --ssl=0
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  medapp_blue:
    build:
      context: .
      dockerfile: dockerfile
    container_name: medapp_blue
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - APP_POOL=medapp_blue
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet
    command:  sh -c "./wait-for-it.sh db:3306 --timeout=30 --strict -- \
              python manage.py runserver 0.0.0.0:8000"

  medapp_green:
    build:
      context: .
      dockerfile: dockerfile
    container_name: medapp_green
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      - APP_POOL=medapp_green
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet
    command:  sh -c "./wait-for-it.sh db:3306 --timeout=30 --strict -- \
              python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    container_name: medapp_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - medapp_blue
      - medapp_green
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:

